#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate js/data.js (window.DATA / window.CV) from the canonical JSON in data/.
Browsers can't fetch() local JSON from file://, so the rate tables are embedded
as a plain script. Run after regenerating data/*.json with the extract scripts.
Usage: python3 scripts/build-data.py"""
import os
HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.dirname(HERE)
prem = open(os.path.join(ROOT, 'data', 'premium.json'), encoding='utf-8').read()
cv = open(os.path.join(ROOT, 'data', 'cashvalue.json'), encoding='utf-8').read()
out = '/* AUTO-GENERATED by scripts/build-data.py — do not edit by hand. */\n'
out += 'window.DATA=' + prem + ';\nwindow.CV=' + cv + ';\n'
dest = os.path.join(ROOT, 'js', 'data.js')
open(dest, 'w', encoding='utf-8').write(out)
print('wrote', dest, round(os.path.getsize(dest) / 1024, 1), 'KB')
