#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Bundle data/premium.json + data/cashvalue.json into js/data.js.
Run after extract.py / extract_cv.py. Output is AUTO-GENERATED — do not hand-edit js/data.js."""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.dirname(HERE)
prem = json.load(open(os.path.join(ROOT, 'data', 'premium.json'), encoding='utf-8'))
cv = json.load(open(os.path.join(ROOT, 'data', 'cashvalue.json'), encoding='utf-8'))
js = ("// AUTO-GENERATED by scripts/build-data.py — do not edit by hand.\n"
      "window.DATA=" + json.dumps(prem, ensure_ascii=False, separators=(',', ':')) + ";\n"
      "window.CV=" + json.dumps(cv, ensure_ascii=False, separators=(',', ':')) + ";\n")
out = os.path.join(ROOT, 'js', 'data.js')
open(out, 'w', encoding='utf-8').write(js)
print('wrote', out, round(os.path.getsize(out) / 1024, 1), 'KB')
